### ISSUE TITLE
[Android] Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by nicolasdevienne** [anttivuor/react-native-switch-audio-output-android#1]
Hi @anttivuor! I use your lib in my project since 2 years and it's OK (React Native version is 0.66.4). I upgrade this project to React Native version 0.72.4 and I can't compile my project, I have this error : "Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.".

React Native version : 0.72.4

react-native-switch-audio-output-android version : 1.0.2

Can you help me ? Thx :)

**Comment by anttivuor** [comment]
Hi! 

I really don't have time to update this project, but this seems like a compiling issue. Could you try this fix that someone made to my other RN package (https://github.com/anttivuor/react-native-start-activity-for-result/commit/4c7a1978353f043e204d7a6e737bac4fae665dda)?

If you find fix for this, PRs are welcome :)

**Comment by nicolasdevienne** [comment]
> Hi!
> 
> I really don't have time to update this project, but this seems like a compiling issue. Could you try this fix that someone made to my other RN package ([anttivuor/react-native-start-activity-for-result@4c7a197](https://github.com/anttivuor/react-native-start-activity-for-result/commit/4c7a1978353f043e204d7a6e737bac4fae665dda))?
> 
> If you find fix for this, PRs are welcome :)

Thx @anttivuor! It works! I have just create a PR :)
